import os
import cx_Oracle
from dotenv import load_dotenv

load_dotenv()

ORACLE_USER = os.getenv("ORACLE_USER")
ORACLE_PASSWORD = os.getenv("ORACLE_PASSWORD")
ORACLE_HOST = os.getenv("ORACLE_HOST")
ORACLE_PORT = os.getenv("ORACLE_PORT")
ORACLE_SERVICE = os.getenv("ORACLE_SERVICE_NAME")

# Oracle DSN
dsn = cx_Oracle.makedsn(ORACLE_HOST, ORACLE_PORT, service_name=ORACLE_SERVICE)

def get_connection():
    return cx_Oracle.connect(
        user=ORACLE_USER,
        password=ORACLE_PASSWORD,
        dsn=dsn
    )

def init_db():
    conn = get_connection()
    cur = conn.cursor()
    try:
        cur.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE employees (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    name VARCHAR2(100) NOT NULL,
                    employee_number VARCHAR2(20) UNIQUE
                )';
            EXCEPTION WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        """)

        cur.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE employee_details (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    emp_id NUMBER REFERENCES employees(id),
                    position VARCHAR2(50),
                    address VARCHAR2(255),
                    status VARCHAR2(20),
                    salary FLOAT,
                    phone VARCHAR2(20) UNIQUE,
                    email VARCHAR2(100) UNIQUE,
                    password VARCHAR2(20),
                    gender VARCHAR2(10),
                    marital VARCHAR2(20),
                    sp NUMBER
                )';
            EXCEPTION WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        """)

        cur.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE absensi (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    emp_id NUMBER REFERENCES employees(id),
                    latitude FLOAT,
                    longitude FLOAT,  
                    addr VARCHAR2(255),
                    dist FLOAT,
                    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    late NUMBER(1),
                    remote NUMBER(1)
                )';
            EXCEPTION WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        """)


        cur.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE leaves (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    emp_id NUMBER REFERENCES employees(id) NOT NULL,
                    remaining_leave NUMBER DEFAULT 12,
                    sick_leave NUMBER DEFAULT 0,
                    maternity_leave NUMBER DEFAULT 0,
                    unpaid_leave NUMBER DEFAULT 0,
                    other_leave NUMBER DEFAULT 0
                )';
            EXCEPTION WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        """)

        cur.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE users (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    email VARCHAR2(100) UNIQUE NOT NULL,
                    password VARCHAR2(100) NOT NULL,
                    jwt_token CLOB, 
                    refresh_token CLOB 
                )';
            EXCEPTION WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        """)

        cur.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE chat_history (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    user_id NUMBER REFERENCES users(id),
                    prompt CLOB,
                    answer CLOB,
                    is_streamed NUMBER(1) DEFAULT 0,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )';
            EXCEPTION WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        """)

        conn.commit()
        print("✅ Tabel berhasil dibuat atau sudah ada.")
    except Exception as e:
        print(f"❌ Gagal inisialisasi tabel: {e}")
        conn.rollback()
    finally:
        cur.close()
        conn.close()


