import sys
import os
# Add parent directory to path so we can import packages if run directly
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir) # backend
sys.path.append(parent_dir)

import cx_Oracle
import datetime
from dotenv import load_dotenv
import bcrypt

load_dotenv()

ORACLE_USER = os.getenv("ORACLE_USER")
ORACLE_PASSWORD = os.getenv("ORACLE_PASSWORD")
ORACLE_HOST = os.getenv("ORACLE_HOST")
ORACLE_PORT = os.getenv("ORACLE_PORT")
ORACLE_SERVICE = os.getenv("ORACLE_SERVICE_NAME")

# Oracle DSN
dsn = cx_Oracle.makedsn(ORACLE_HOST, ORACLE_PORT, service_name=ORACLE_SERVICE)

def get_connection():
    return cx_Oracle.connect(
        user=ORACLE_USER,
        password=ORACLE_PASSWORD,
        dsn=dsn
    )

def init_db():
    conn = get_connection()
    cur = conn.cursor()
    try:
        # 1. EMPLOYEES Table
        cur.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE employees (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    employee_code VARCHAR2(20) UNIQUE NOT NULL,
                    name VARCHAR2(100) NOT NULL,
                    email VARCHAR2(100) UNIQUE NOT NULL,
                    phone VARCHAR2(20),
                    department VARCHAR2(50) NOT NULL,
                    position VARCHAR2(50) NOT NULL,
                    status VARCHAR2(20) DEFAULT ''active'',
                    address CLOB,
                    marital_status VARCHAR2(20),
                    basic_salary NUMBER,
                    bpjs_number VARCHAR2(50),
                    remaining_leave NUMBER DEFAULT 12,
                    employment_status VARCHAR2(20),
                    sp_level NUMBER DEFAULT 0,
                    joined_at DATE NOT NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )';
            EXCEPTION WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        """)

        # 2. HR_USERS Table (Replaces old users table)
        cur.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE hr_users (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    username VARCHAR2(50) UNIQUE NOT NULL,
                    email VARCHAR2(100) UNIQUE NOT NULL,
                    password_hash VARCHAR2(255) NOT NULL,
                    full_name VARCHAR2(100) NOT NULL,
                    role VARCHAR2(20) DEFAULT ''hr_staff'',
                    is_active NUMBER(1) DEFAULT 1,
                    last_login TIMESTAMP,
                    jwt_token CLOB, 
                    refresh_token CLOB,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )';
            EXCEPTION WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        """)

        # 3. ATTENDANCE Table
        cur.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE attendance (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    employee_id NUMBER REFERENCES employees(id) ON DELETE CASCADE NOT NULL,
                    attendance_date DATE NOT NULL,
                    check_in TIMESTAMP,
                    check_out TIMESTAMP,
                    work_location VARCHAR2(20) NOT NULL,
                    status VARCHAR2(20) NOT NULL,
                    notes CLOB,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT uq_attendance_emp_date UNIQUE (employee_id, attendance_date)
                )';
            EXCEPTION WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
                IF SQLCODE = -2261 THEN NULL; END IF; -- Unique key already exists
                IF SQLCODE = -2264 THEN NULL; END IF; -- Constraint already exists
            END;
        """)

        # 4. WARNINGS Table
        cur.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE warnings (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    employee_id NUMBER REFERENCES employees(id) ON DELETE CASCADE NOT NULL,
                    warning_type VARCHAR2(10) NOT NULL,
                    reason CLOB NOT NULL,
                    issued_date DATE NOT NULL,
                    issued_by NUMBER REFERENCES hr_users(id) ON DELETE SET NULL,
                    email_sent NUMBER(1) DEFAULT 0,
                    email_sent_at TIMESTAMP,
                    document_path VARCHAR2(255),
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )';
            EXCEPTION WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        """)

        # 5. CONVERSATIONS Table
        cur.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE conversations (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    user_id NUMBER REFERENCES hr_users(id) ON DELETE CASCADE NOT NULL,
                    title VARCHAR2(255),
                    is_active NUMBER(1) DEFAULT 1,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )';
            EXCEPTION WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        """)

        # 6. MESSAGES Table
        cur.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE messages (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    conversation_id NUMBER REFERENCES conversations(id) ON DELETE CASCADE NOT NULL,
                    role VARCHAR2(20) NOT NULL,
                    content CLOB NOT NULL,
                    token_count NUMBER,
                    tool_calls CLOB,
                    message_metadata CLOB,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )';
            EXCEPTION WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        """)

        # 7. DOCUMENTS Table (RAG)
        cur.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE documents (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    title VARCHAR2(255) NOT NULL,
                    doc_type VARCHAR2(50) NOT NULL,
                    file_path VARCHAR2(500),
                    content_hash VARCHAR2(64),
                    chunk_count NUMBER DEFAULT 0,
                    is_active NUMBER(1) DEFAULT 1,
                    uploaded_by NUMBER REFERENCES hr_users(id) ON DELETE SET NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )';
            EXCEPTION WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        """)

        # 8. MIGRATION / SAFETY ALTER TABLES
        # Ensure message_metadata exists for existing databases
        cur.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'ALTER TABLE messages ADD message_metadata CLOB';
            EXCEPTION WHEN OTHERS THEN
                IF SQLCODE != -1430 THEN RAISE; END IF; -- ORA-01430: column being added already exists (ignored)
            END;
        """)

        # 9. PROCESSING_STAGES Table (for persisting agent processing state)
        cur.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE processing_stages (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    conversation_id NUMBER REFERENCES conversations(id) ON DELETE CASCADE NOT NULL,
                    stage_number NUMBER NOT NULL,
                    stage_name VARCHAR2(100) NOT NULL,
                    content CLOB,
                    status VARCHAR2(20) DEFAULT ''processing'',
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
                )';
            EXCEPTION WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        """)

        # 10. PAYROLL_SLIPS Table (Monthly salary slips)
        cur.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE payroll_slips (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    employee_id NUMBER REFERENCES employees(id) ON DELETE CASCADE NOT NULL,
                    period_month NUMBER NOT NULL,
                    period_year NUMBER NOT NULL,
                    basic_salary NUMBER DEFAULT 0,
                    overtime_pay NUMBER DEFAULT 0,
                    bonus NUMBER DEFAULT 0,
                    allowance_transport NUMBER DEFAULT 0,
                    allowance_meal NUMBER DEFAULT 0,
                    allowance_housing NUMBER DEFAULT 0,
                    allowance_communication NUMBER DEFAULT 0,
                    allowance_other NUMBER DEFAULT 0,
                    deduction_bpjs_kesehatan NUMBER DEFAULT 0,
                    deduction_bpjs_ketenagakerjaan NUMBER DEFAULT 0,
                    deduction_pph21 NUMBER DEFAULT 0,
                    deduction_loan NUMBER DEFAULT 0,
                    deduction_absence NUMBER DEFAULT 0,
                    deduction_other NUMBER DEFAULT 0,
                    gross_salary NUMBER DEFAULT 0,
                    total_deductions NUMBER DEFAULT 0,
                    net_salary NUMBER DEFAULT 0,
                    payment_date DATE,
                    payment_method VARCHAR2(50),
                    bank_account VARCHAR2(50),
                    notes CLOB,
                    file_path VARCHAR2(500),
                    download_url VARCHAR2(500),
                    status VARCHAR2(20) DEFAULT ''draft'',
                    generated_by NUMBER REFERENCES hr_users(id) ON DELETE SET NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT uq_payroll_emp_period UNIQUE (employee_id, period_month, period_year)
                )';
            EXCEPTION WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        """)

        # 11. EMPLOYEE_CV Table (Employee CV / profile with deductions)
        cur.execute("""
            BEGIN
                EXECUTE IMMEDIATE 'CREATE TABLE employee_cv (
                    id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
                    employee_id NUMBER REFERENCES employees(id) ON DELETE CASCADE NOT NULL,
                    current_position VARCHAR2(100),
                    current_department VARCHAR2(100),
                    current_salary NUMBER DEFAULT 0,
                    education_level VARCHAR2(50),
                    education_institution VARCHAR2(200),
                    education_major VARCHAR2(100),
                    graduation_year NUMBER,
                    certifications CLOB,
                    skills CLOB,
                    work_experience CLOB,
                    emergency_contact_name VARCHAR2(100),
                    emergency_contact_phone VARCHAR2(20),
                    emergency_contact_relation VARCHAR2(50),
                    blood_type VARCHAR2(5),
                    religion VARCHAR2(30),
                    ktp_number VARCHAR2(30),
                    npwp_number VARCHAR2(30),
                    bank_name VARCHAR2(50),
                    bank_account_number VARCHAR2(50),
                    bank_account_name VARCHAR2(100),
                    deduction_bpjs_kesehatan NUMBER DEFAULT 0,
                    deduction_bpjs_ketenagakerjaan NUMBER DEFAULT 0,
                    deduction_meal NUMBER DEFAULT 0,
                    deduction_transport NUMBER DEFAULT 0,
                    deduction_insurance NUMBER DEFAULT 0,
                    deduction_laptop_installment NUMBER DEFAULT 0,
                    deduction_laptop_remaining_months NUMBER DEFAULT 0,
                    deduction_other NUMBER DEFAULT 0,
                    deduction_other_description VARCHAR2(255),
                    total_monthly_deductions NUMBER DEFAULT 0,
                    file_path VARCHAR2(500),
                    download_url VARCHAR2(500),
                    notes CLOB,
                    last_updated_by NUMBER REFERENCES hr_users(id) ON DELETE SET NULL,
                    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                    CONSTRAINT uq_employee_cv UNIQUE (employee_id)
                )';
            EXCEPTION WHEN OTHERS THEN
                IF SQLCODE != -955 THEN RAISE; END IF;
            END;
        """)


        conn.commit()
        print("Tables initialized successfully.")
        
    except Exception as e:
        print(f"Failed to initialize database: {e}")
        conn.rollback()
    finally:
        cur.close()
        conn.close()
        
    # Run rich seeding
    # Using relative import because we modified sys.path to include 'backend'
    # 'database' is a package in 'backend'
    from database.seed import seed_all
    seed_all()

if __name__ == "__main__":
    init_db()
